apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: devops
  template:
    metadata:
      labels: 
        app: devops
    spec:
      containers:
      - name: devops
        image: gcr.io/noble-safeguard-250717/devops:v0.1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: devops-loadbalancer
  labels:
    app: devops-svc
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: devops
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: devops
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60